pool:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- bash: 'npm i -g azure-functions-core-tools --unsafe-perm true'
  displayName: 'Install Azure Functions CLI'

- bash: 'func extensions install'
  workingDirectory: 'function-app'
  displayName: 'Install Azure Functions Extensions'

- bash: yarn
  workingDirectory: 'function-app'
  displayName: 'Install npm dependencies using yarn'

- task: DeleteFiles@1
  displayName: 'Delete .vscode folder'
  inputs:
    contents: function-app\.vscode

- bash: 'cp "$(which node.exe)" .'
  workingDirectory: 'function-app'
  displayName: 'Copy node.exe for deployment'

- task: ArchiveFiles@2
  displayName: 'Create build artifact zip'
  inputs:
    rootFolderOrFile: 'function-app'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
