# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn
  displayName: 'yarn install'
  workingDirectory: node-function-app

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)\node-function-app'
    includeRootFolder: true
    archiveType: zip
    replaceExistingArchive: true
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'