pool:
  name: Hosted VS2017
steps:
- task: NodeTool@0
  displayName: 'Use Node 10.15.3'
  inputs:
    versionSpec: 10.15.3

- base: 'cp "$(which node.exe)" .'
  workingDirectory: 'function-app'
  displayName: 'copy node.exe for deployment'

- task: DeleteFiles@1
  inputs:
    contents: function-app\.vscode

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: 'function-app'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
